# Generated by Django 4.1.6 on 2023-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="To_do",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок задачи",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Кратко опишите задачу",
                        max_length=200,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        null=True,
                        verbose_name="Текстовое поле",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "НОВАЯ"),
                            ("IN_PROGRESS", "В ПРОЦЕССЕ"),
                            ("FINISHED", "СДЕЛАНО"),
                        ],
                        default="NEW",
                        help_text="Статус задачи",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "execution_date",
                    models.CharField(
                        blank=True,
                        help_text="Введите в формате ГГГГ-ММ-ДД",
                        max_length=10,
                        null=True,
                        verbose_name="Дата исполнения",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
